apiVersion: v1
kind: Service
metadata:
  name: skin-lesion-api-service
spec:
  type: NodePort
  selector:
    app: skin-lesion-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080